language: erlang
otp_release:
  - 21.3
  - 22.2
install:
  - make
  - ./rebar3 update
  - travis_wait 30 mvn install
script:
  - make test
  - make proper
  - make coverage
  - ./rebar3 as test coveralls send
  - make lint
  - make xref
  - make dialyzer
  - make docs
sudo: required
dist: trusty
