name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        erlang: [ 21,22,23 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile
    - name: Format
      run: make format
    - name: Unit Tests
      run: make test
    - name: Property-Based Tests
      run: make proper
    - name: Coverage
      run: make coverage
    - name: Lint
      run: make lint
    - name: XRef
      run: make xref
    - name: Dialyzer
      run: make dialyzer
    - name: Documentation
      run: make docs
    - name: Send Coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./rebar3 as test coveralls send
    

    
    - name: Checkout rclref
      uses: actions/checkout@v2
      with:
        repository: clone https://github.com/wattlebirdaz/rclref.git
        path: ~/rclref
  
    - name: Cache build
      uses: actions/cache@v1
      with:
        path: ~/rclref/_checkouts/riak_core
        key: ${{ runner.OS }}-build-test

    - name: Checkout riak
      run: |
        ls -R
        make ct
     
      

